/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pt.isel.mpd;

import org.junit.Test;
import pt.isel.mpd.util.HttpRequest;
import pt.isel.mpd.util.LazyQueries;
import pt.isel.mpd.util.MockRequest;
import pt.isel.mpd.weather.WeatherInfo;
import pt.isel.mpd.weather.WeatherWebApi;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Random;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static pt.isel.mpd.util.LazyQueries.*;

public class LazyQueriesTest {
    final Iterable<WeatherInfo> jan;

    public LazyQueriesTest() {
       //WeatherWebApi api = new WeatherWebApi(new MockRequest());
       //jan = api.pastWeather(37.017, -7.933, LocalDate.of(2020, 1, 1), LocalDate.of(2020, 1, 30));
        jan=null;
    }

    @Test public void testGenerateRandomIntegers() {
        Random rand = new Random();
        Iterator<Integer> nrs = generate(rand::nextInt).iterator();
        System.out.println(nrs.next());
        System.out.println(nrs.next());
        System.out.println(nrs.next());
    }
    int init;
    @Test public void testGenerateEvenIntegers() {
        Iterator<Integer> expected = Arrays.asList(0, 2, 4, 6).iterator();
        init = 0;
        Iterable<Integer> actual = limit(filter(generate(() -> init++), n -> n % 2 == 0), 4);
        actual.forEach(curr -> assertEquals(expected.next(), curr));
        assertFalse(expected.hasNext());
    }

    @Test public void testMaxTemperatureOnJanuary() {
        int maxTemp = max(map(jan, WeatherInfo::getTempC));
        assertEquals(17, maxTemp);
    }

    @Test public void testMaxTemperatureOnSunnyDays() {
        int maxTemp = max(map(filter(jan, wi -> wi.getDesc().contains("Sun")), WeatherInfo::getTempC));
        assertEquals(15, maxTemp);
    }

    @Test public void testFilterCloudyDays() {
        Iterable<WeatherInfo> cloud = filter(jan, LazyQueriesTest::cloudyDays);
        assertEquals(14, LazyQueries.count(cloud));
    }

    @Test public void filterEvenNumbers() {
        Iterable<Integer> nrs = Arrays.asList(1, 2, 3, 4, 5, 6, 7);
        Iterator<Integer> expected = Arrays.asList(2, 4, 6).iterator();
        Iterator<Integer> actual = filter(nrs, n -> n % 2 == 0).iterator();
        while(actual.hasNext()) {
            Integer curr = actual.next();
            assertEquals(expected.next(), curr);
        }
        assertFalse(expected.hasNext());
    }

    @Test public void distinctNumbers() {
        Iterable<Integer> nrs = Arrays.asList(1, 2, 3, 4, 5, 6, 7,7,6,5,4,0,8,2,1);
        Iterator<Integer> expected = Arrays.asList(1,2,3,4,5,6,7,0,8).iterator();
        Iterator<Integer> actual = distinct(nrs).iterator();
        while(actual.hasNext()) {
            Integer curr = actual.next();
            assertEquals(expected.next(), curr);
        }
        assertFalse(expected.hasNext());
    }

    @Test public void concatNumbers() {
        Iterable<Integer> nrs1 = Arrays.asList(1, 2, 3);
        Iterable<Integer> nrs2 = Arrays.asList(4,5,6,7,8,9,10);
        Iterator<Integer> expected = Arrays.asList(1,2,3,4,5,6,7,8,9,10).iterator();
        Iterator<Integer> actual = concat(nrs1,nrs2).iterator();
        while(actual.hasNext()) {
            Integer curr = actual.next();
            assertEquals(expected.next(), curr);
        }
        assertFalse(expected.hasNext());
    }

    @Test public void interleaveNumbers() {
        Iterable<Integer> nrs1 = Arrays.asList(1,2,3);
        Iterable<Integer> nrs2 = Arrays.asList(4,5,6,7,8,9,10);
        Iterator<Integer> expected = Arrays.asList(1,4,2,5,3,6,7,8,9,10).iterator();
        Iterator<Integer> actual = interleave(nrs1,nrs2).iterator();
        while(actual.hasNext()) {
            Integer curr = actual.next();
            assertEquals(expected.next(), curr);
        }
        assertFalse(expected.hasNext());
    }

    @Test public void interleaveNumbersEmpty() {
        Iterable<Integer> nrs1 = Arrays.asList();
        Iterable<Integer> nrs2 = Arrays.asList(4,5,6,7,8,9,10);
        Iterator<Integer> expected = Arrays.asList(4,5,6,7,8,9,10).iterator();
        Iterator<Integer> actual = interleave(nrs1,nrs2).iterator();
        while(actual.hasNext()) {
            Integer curr = actual.next();
            assertEquals(expected.next(), curr);
        }
        assertFalse(expected.hasNext());
    }

    static boolean cloudyDays(WeatherInfo info) {
        return info.desc.toLowerCase().contains("cloud");
    }

}
